export const FETCH_JOKES_BEGIN = 'FETCH_JOKES_BEGIN';
export const FETCH_FAVORITE_JOKES_BEGIN = 'FETCH_FAVORITE_JOKES_BEGIN';
export const FETCH_JOKES_SUCCESS = 'FETCH_JOKES_SUCCESS';
export const FETCH_FAVORITE_JOKES_SUCCESS = 'FETCH_FAVORITE_JOKES_SUCCESS';
export const FETCH_JOKES_ERROR = 'FETCH_JOKES_ERROR';
export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES';
